local M = {}

function M.highlights(palette)
	local highlights = {
		Normal = { fg = palette.fg, bg = palette.bg },
		NormalNC = { fg = palette.fg, bg = palette.bg },
		NormalFloat = { fg = palette.fg, bg = palette.surface_alt },
		FloatBorder = { fg = palette.border, bg = palette.surface_alt },
		FloatTitle = { fg = palette.accent, bg = palette.surface_alt, bold = true },
		ColorColumn = { bg = palette.surface },
		Conceal = { fg = palette.comment },
		Cursor = { fg = palette.bg, bg = palette.cursor },
		lCursor = { fg = palette.bg, bg = palette.cursor },
		CursorLine = { bg = palette.line },
		CursorColumn = { bg = palette.surface },
		CursorLineNr = { fg = palette.type_ref, bold = true },
		LineNr = { fg = palette.punct },
		SignColumn = { fg = palette.punct, bg = palette.bg },
		FoldColumn = { fg = palette.comment, bg = palette.bg },
		Folded = { fg = palette.comment, bg = palette.surface },
		Visual = { bg = palette.selection },
		VisualNOS = { bg = palette.selection },
		Search = { fg = palette.search_fg, bg = palette.search_bg },
		CurSearch = { fg = palette.cur_search_fg, bg = palette.cur_search_bg, bold = true },
		Substitute = { fg = palette.cur_search_fg, bg = palette.cur_search_bg, bold = true },
		MatchParen = { fg = palette.accent, bg = palette.selection, bold = true },
		Directory = { fg = palette.accent },
		Title = { fg = palette.fg, bold = true },
		ErrorMsg = { fg = palette.error, bg = palette.bg, bold = true },
		WarningMsg = { fg = palette.warning, bg = palette.bg, bold = true },
		MoreMsg = { fg = palette.accent },
		ModeMsg = { fg = palette.accent },
		Question = { fg = palette.accent },
		NonText = { fg = palette.border },
		Whitespace = { fg = palette.border },
		SpecialKey = { fg = palette.comment },
		EndOfBuffer = { fg = palette.bg },
		WinSeparator = { fg = palette.border, bg = palette.bg },
		StatusLine = { fg = palette.fg, bg = palette.surface_alt },
		StatusLineNC = { fg = palette.comment, bg = palette.bg },
		TabLine = { fg = palette.comment, bg = palette.surface },
		TabLineFill = { fg = palette.comment, bg = palette.bg },
		TabLineSel = { fg = palette.fg, bg = palette.surface_alt },
		Pmenu = { fg = palette.fg, bg = palette.surface_alt },
		PmenuSel = { fg = palette.fg, bg = palette.surface },
		PmenuSbar = { bg = palette.surface },
		PmenuThumb = { bg = palette.border },
		WildMenu = { fg = palette.bg, bg = palette.accent },
		QuickFixLine = { bg = palette.surface },
		Comment = { fg = palette.comment },
		Todo = { fg = palette.bg, bg = palette.accent, bold = true },
		Keyword = { fg = palette.keyword },
		Operator = { fg = palette.punct },
		Delimiter = { fg = palette.punct },
		Special = { fg = palette.accent },
		Identifier = { fg = palette.fg },
		Function = { fg = palette.fg },
		String = { fg = palette.accent },
		Number = { fg = palette.accent },
		Boolean = { fg = palette.accent },
		Constant = { fg = palette.fg },
		Type = { fg = palette.type_ref },
		Typedef = { fg = palette.fg },
		Label = { fg = palette.fg },
		Tag = { fg = palette.fg },
		Underlined = { fg = palette.accent, underline = true },
		Error = { fg = palette.error },
		DiffAdd = { bg = palette.diff_add_bg },
		DiffChange = { bg = palette.diff_change_bg },
		DiffDelete = { bg = palette.diff_delete_bg },
		DiffText = { fg = palette.accent, bg = palette.diff_change_bg, bold = true },
		GitSignsAdd = { fg = palette.git_add, bg = palette.bg },
		GitSignsChange = { fg = palette.git_change, bg = palette.bg },
		GitSignsDelete = { fg = palette.git_delete, bg = palette.bg },
		DiagnosticError = { fg = palette.error },
		DiagnosticWarn = { fg = palette.warning },
		DiagnosticInfo = { fg = palette.info },
		DiagnosticHint = { fg = palette.comment },
		DiagnosticOk = { fg = palette.success },
		DiagnosticVirtualTextError = { fg = palette.error, bg = palette.diff_delete_bg },
		DiagnosticVirtualTextWarn = { fg = palette.warning, bg = palette.diff_change_bg },
		DiagnosticVirtualTextInfo = { fg = palette.info, bg = palette.surface },
		DiagnosticVirtualTextHint = { fg = palette.comment, bg = palette.surface },
		DiagnosticUnderlineError = { undercurl = true, sp = palette.error },
		DiagnosticUnderlineWarn = { undercurl = true, sp = palette.warning },
		DiagnosticUnderlineInfo = { undercurl = true, sp = palette.info },
		DiagnosticUnderlineHint = { undercurl = true, sp = palette.comment },
		TelescopeNormal = { fg = palette.fg, bg = palette.surface_alt },
		TelescopeBorder = { fg = palette.border, bg = palette.surface_alt },
		TelescopePromptNormal = { fg = palette.fg, bg = palette.surface_alt },
		TelescopePromptBorder = { fg = palette.border, bg = palette.surface_alt },
		TelescopePromptTitle = { fg = palette.bg, bg = palette.accent_strong, bold = true },
		TelescopePreviewTitle = { fg = palette.bg, bg = palette.comment, bold = true },
		TelescopeResultsTitle = { fg = palette.bg, bg = palette.type_ref, bold = true },
		TelescopeSelection = { bg = palette.surface },
		TelescopeMatching = { fg = palette.accent, bold = true },
	}

	local links = {
		IncSearch = "CurSearch",
		SpecialComment = "Comment",
		Character = "String",
		Float = "Number",
		Conditional = "Keyword",
		Repeat = "Keyword",
		Statement = "Keyword",
		PreProc = "Keyword",
		Include = "Keyword",
		Define = "Keyword",
		Macro = "Keyword",
		StorageClass = "Keyword",
		Structure = "Keyword",
		Exception = "Keyword",
		VertSplit = "WinSeparator",
		["@annotation"] = "Comment",
		["@comment"] = "Comment",
		["@comment.documentation"] = "Comment",
		["@comment.error"] = "DiagnosticError",
		["@comment.warning"] = "DiagnosticWarn",
		["@comment.todo"] = "Todo",
		["@comment.note"] = "DiagnosticInfo",
		["@keyword"] = "Keyword",
		["@keyword.conditional"] = "Keyword",
		["@keyword.repeat"] = "Keyword",
		["@keyword.return"] = "Keyword",
		["@keyword.operator"] = "Keyword",
		["@keyword.exception"] = "Keyword",
		["@keyword.import"] = "Keyword",
		["@keyword.directive"] = "Keyword",
		["@keyword.function"] = "Keyword",
		["@operator"] = "Operator",
		["@punctuation"] = "Delimiter",
		["@punctuation.bracket"] = "Delimiter",
		["@punctuation.delimiter"] = "Delimiter",
		["@string"] = "String",
		["@string.documentation"] = "String",
		["@string.escape"] = "String",
		["@string.regex"] = "String",
		["@string.special"] = "String",
		["@character"] = "String",
		["@character.special"] = "String",
		["@number"] = "Number",
		["@number.float"] = "Float",
		["@boolean"] = "Boolean",
		["@constant"] = "Constant",
		["@constant.builtin"] = "Type",
		["@constant.macro"] = "Constant",
		["@module"] = "Identifier",
		["@namespace"] = "Identifier",
		["@symbol"] = "Constant",
		["@variable"] = "Identifier",
		["@variable.builtin"] = "Identifier",
		["@variable.parameter"] = "Identifier",
		["@variable.parameter.builtin"] = "Identifier",
		["@variable.member"] = "Identifier",
		["@property"] = "Identifier",
		["@field"] = "Identifier",
		["@constructor"] = "Identifier",
		["@function"] = "Function",
		["@function.builtin"] = "Function",
		["@function.call"] = "Function",
		["@function.macro"] = "Function",
		["@method"] = "Function",
		["@method.call"] = "Function",
		["@function.method"] = "Function",
		["@type"] = "Type",
		["@type.builtin"] = "Type",
		["@type.definition"] = "Identifier",
		["@attribute"] = "Identifier",
		["@tag"] = "Tag",
		["@tag.attribute"] = "Identifier",
		["@tag.delimiter"] = "Delimiter",
		["@markup.heading"] = "Title",
		["@markup.heading.1"] = "Title",
		["@markup.heading.2"] = "Title",
		["@markup.heading.3"] = "Title",
		["@markup.heading.4"] = "Title",
		["@markup.heading.5"] = "Title",
		["@markup.heading.6"] = "Title",
		["@markup.list"] = "Keyword",
		["@markup.link"] = "Identifier",
		["@markup.link.label"] = "Identifier",
		["@markup.link.url"] = "Underlined",
		["@markup.raw"] = "String",
		["@markup.quote"] = "Comment",
		["@markup.math"] = "String",
		["@markup.strikethrough"] = "Comment",
		["@diff.plus"] = "DiffAdd",
		["@diff.minus"] = "DiffDelete",
		["@diff.delta"] = "DiffChange",
		["@lsp.type.class"] = "Type",
		["@lsp.type.interface"] = "Type",
		["@lsp.type.type"] = "Type",
		["@lsp.type.struct"] = "Type",
		["@lsp.type.enum"] = "Type",
		["@lsp.type.typeParameter"] = "Identifier",
		["@lsp.type.parameter"] = "Identifier",
		["@lsp.type.property"] = "Identifier",
		["@lsp.type.variable"] = "Identifier",
		["@lsp.type.namespace"] = "Identifier",
		["@lsp.type.function"] = "Function",
		["@lsp.type.method"] = "Function",
		["@lsp.type.enumMember"] = "Constant",
		["@lsp.type.keyword"] = "Keyword",
		["@lsp.typemod.class.declaration"] = "Identifier",
		["@lsp.typemod.interface.declaration"] = "Identifier",
		["@lsp.typemod.type.declaration"] = "Identifier",
		["@lsp.typemod.enum.declaration"] = "Identifier",
		["@lsp.typemod.type.defaultLibrary"] = "Type",
		["@lsp.typemod.variable.defaultLibrary"] = "Type",
		["@lsp.typemod.variable.readonly"] = "Constant",
		["@lsp.typemod.property.readonly"] = "Constant",
		htmlTag = "Tag",
		htmlEndTag = "Tag",
		htmlTagName = "Tag",
		htmlArg = "Identifier",
		htmlString = "String",
	}

	for group, link in pairs(links) do
		highlights[group] = { link = link }
	end

	highlights["@markup.italic"] = { fg = palette.fg, italic = true }
	highlights["@markup.emphasis"] = { fg = palette.fg, italic = true }
	highlights["@markup.strong"] = { fg = palette.fg, bold = true }
	highlights["markdownItalic"] = { fg = palette.fg, italic = true }
	highlights["markdownBold"] = { fg = palette.fg, bold = true }

	return highlights
end

return M
